import type { Product } from './store-types'

export const products: Product[] = [
  // HOMBRE
  {
    id: 'h-001',
    nombre: 'Saguaro Pro Runner',
    descripcion: 'Zapatilla barefoot de alto rendimiento para running. Suela ultrafina de 5mm que te permite sentir cada paso mientras proteges tus pies.',
    precio: 54990,
    precioOriginal: 69990,
    categoria: 'hombre',
    tipo: 'running',
    imagenes: ['/products/h-runner-1.jpg'],
    tallas: [
      { talla: 40, stock: 5 },
      { talla: 41, stock: 8 },
      { talla: 42, stock: 12 },
      { talla: 43, stock: 10 },
      { talla: 44, stock: 6 },
      { talla: 45, stock: 3 },
    ],
    colores: ['Negro', 'Gris', 'Azul'],
    caracteristicas: ['Suela 5mm', 'Puntera ancha', 'Zero drop', 'Transpirable', 'Peso: 180g'],
    destacado: true,
    nuevo: false,
    descuento: 21,
  },
  {
    id: 'h-002',
    nombre: 'Saguaro Urban Flex',
    descripcion: 'Calzado casual barefoot perfecto para el día a día. Combina estilo urbano con la comodidad natural de un calzado minimalista.',
    precio: 44990,
    categoria: 'hombre',
    tipo: 'casual',
    imagenes: ['/products/h-casual-1.jpg'],
    tallas: [
      { talla: 40, stock: 10 },
      { talla: 41, stock: 15 },
      { talla: 42, stock: 20 },
      { talla: 43, stock: 18 },
      { talla: 44, stock: 8 },
    ],
    colores: ['Negro', 'Marron', 'Blanco'],
    caracteristicas: ['Suela flexible', 'Cuero sintetico', 'Zero drop', 'Plantilla removible'],
    destacado: true,
    nuevo: true,
  },
  {
    id: 'h-003',
    nombre: 'Saguaro Trek Mountain',
    descripcion: 'Bota de trekking barefoot con agarre superior. Ideal para senderos y terrenos irregulares manteniendo la sensacion natural.',
    precio: 74990,
    categoria: 'hombre',
    tipo: 'trekking',
    imagenes: ['/products/h-trek-1.jpg'],
    tallas: [
      { talla: 40, stock: 4 },
      { talla: 41, stock: 6 },
      { talla: 42, stock: 8 },
      { talla: 43, stock: 7 },
      { talla: 44, stock: 5 },
    ],
    colores: ['Verde Militar', 'Negro', 'Cafe'],
    caracteristicas: ['Suela Vibram', 'Impermeables', 'Tobillo alto', 'Agarre extremo'],
    destacado: false,
    nuevo: false,
  },
  {
    id: 'h-004',
    nombre: 'Saguaro Aqua Sport',
    descripcion: 'Calzado acuático de secado rápido. Perfecto para playa, kayak o cualquier deporte acuático.',
    precio: 29990,
    categoria: 'hombre',
    tipo: 'acuatico',
    imagenes: ['/products/h-aqua-1.jpg'],
    tallas: [
      { talla: 40, stock: 12 },
      { talla: 41, stock: 15 },
      { talla: 42, stock: 18 },
      { talla: 43, stock: 14 },
      { talla: 44, stock: 10 },
    ],
    colores: ['Azul', 'Negro', 'Gris'],
    caracteristicas: ['Secado rapido', 'Drenaje de agua', 'Suela antideslizante', 'Ultraligero'],
    destacado: false,
    nuevo: true,
  },

  // MUJER
  {
    id: 'm-001',
    nombre: 'Saguaro Bella Run',
    descripcion: 'Zapatilla de running barefoot diseñada específicamente para el pie femenino. Ligereza y estilo en cada zancada.',
    precio: 52990,
    precioOriginal: 64990,
    categoria: 'mujer',
    tipo: 'running',
    imagenes: ['/products/m-runner-1.jpg'],
    tallas: [
      { talla: 35, stock: 6 },
      { talla: 36, stock: 10 },
      { talla: 37, stock: 15 },
      { talla: 38, stock: 12 },
      { talla: 39, stock: 8 },
      { talla: 40, stock: 4 },
    ],
    colores: ['Rosa', 'Negro', 'Blanco', 'Coral'],
    caracteristicas: ['Suela 5mm', 'Puntera ancha', 'Zero drop', 'Transpirable', 'Peso: 150g'],
    destacado: true,
    nuevo: false,
    descuento: 18,
  },
  {
    id: 'm-002',
    nombre: 'Saguaro Elegance',
    descripcion: 'Ballerina barefoot elegante para ocasiones especiales. Demuestra que la comodidad y el estilo pueden ir juntos.',
    precio: 39990,
    categoria: 'mujer',
    tipo: 'casual',
    imagenes: ['/products/m-elegance-1.jpg'],
    tallas: [
      { talla: 35, stock: 8 },
      { talla: 36, stock: 12 },
      { talla: 37, stock: 16 },
      { talla: 38, stock: 14 },
      { talla: 39, stock: 10 },
    ],
    colores: ['Negro', 'Nude', 'Rojo'],
    caracteristicas: ['Suela ultrafina', 'Cuero genuino', 'Plantilla acolchada', 'Elegante'],
    destacado: true,
    nuevo: true,
  },
  {
    id: 'm-003',
    nombre: 'Saguaro Trail Woman',
    descripcion: 'Zapatilla de trail running para mujer. Agarre superior y proteccion en terrenos tecnicos.',
    precio: 64990,
    categoria: 'mujer',
    tipo: 'trekking',
    imagenes: ['/products/m-trail-1.jpg'],
    tallas: [
      { talla: 35, stock: 5 },
      { talla: 36, stock: 7 },
      { talla: 37, stock: 10 },
      { talla: 38, stock: 9 },
      { talla: 39, stock: 6 },
    ],
    colores: ['Morado', 'Negro', 'Turquesa'],
    caracteristicas: ['Suela Vibram', 'Proteccion delantera', 'Zero drop', 'Malla transpirable'],
    destacado: false,
    nuevo: false,
  },
  {
    id: 'm-004',
    nombre: 'Saguaro Beach',
    descripcion: 'Sandalia barefoot perfecta para el verano. Maxima libertad para tus pies.',
    precio: 34990,
    categoria: 'mujer',
    tipo: 'sandalias',
    imagenes: ['/products/m-sandal-1.jpg'],
    tallas: [
      { talla: 35, stock: 10 },
      { talla: 36, stock: 14 },
      { talla: 37, stock: 18 },
      { talla: 38, stock: 16 },
      { talla: 39, stock: 12 },
    ],
    colores: ['Blanco', 'Negro', 'Marron'],
    caracteristicas: ['Correas ajustables', 'Suela flexible', 'Secado rapido', 'Ultraliviana'],
    destacado: false,
    nuevo: true,
  },

  // NIÑOS
  {
    id: 'n-001',
    nombre: 'Saguaro Kids Runner',
    descripcion: 'Zapatilla barefoot para niños activos. Favorece el desarrollo natural del pie infantil.',
    precio: 34990,
    precioOriginal: 42990,
    categoria: 'nino',
    tipo: 'running',
    imagenes: ['/products/n-runner-1.jpg'],
    tallas: [
      { talla: 28, stock: 8 },
      { talla: 29, stock: 10 },
      { talla: 30, stock: 12 },
      { talla: 31, stock: 14 },
      { talla: 32, stock: 12 },
      { talla: 33, stock: 10 },
      { talla: 34, stock: 8 },
    ],
    colores: ['Azul', 'Rojo', 'Verde'],
    caracteristicas: ['Suela flexible', 'Facil de poner', 'Zero drop', 'Lavable', 'Refuerzos'],
    destacado: true,
    nuevo: false,
    descuento: 19,
  },
  {
    id: 'n-002',
    nombre: 'Saguaro School',
    descripcion: 'Calzado escolar barefoot. Comodidad para todo el dia de clases sin sacrificar el desarrollo del pie.',
    precio: 32990,
    categoria: 'nino',
    tipo: 'casual',
    imagenes: ['/products/n-school-1.jpg'],
    tallas: [
      { talla: 28, stock: 15 },
      { talla: 29, stock: 18 },
      { talla: 30, stock: 20 },
      { talla: 31, stock: 22 },
      { talla: 32, stock: 20 },
      { talla: 33, stock: 16 },
      { talla: 34, stock: 12 },
    ],
    colores: ['Negro'],
    caracteristicas: ['Resistente', 'Facil limpieza', 'Velcro', 'Puntera reforzada'],
    destacado: true,
    nuevo: false,
  },
  {
    id: 'n-003',
    nombre: 'Saguaro Kids Aqua',
    descripcion: 'Calzado acuático para niños. Protección y libertad en la playa o piscina.',
    precio: 24990,
    categoria: 'nino',
    tipo: 'acuatico',
    imagenes: ['/products/n-aqua-1.jpg'],
    tallas: [
      { talla: 28, stock: 12 },
      { talla: 29, stock: 14 },
      { talla: 30, stock: 16 },
      { talla: 31, stock: 18 },
      { talla: 32, stock: 16 },
      { talla: 33, stock: 14 },
    ],
    colores: ['Azul', 'Rosa', 'Verde'],
    caracteristicas: ['Secado rapido', 'Antideslizante', 'Elastico', 'Colores vivos'],
    destacado: false,
    nuevo: true,
  },
  {
    id: 'n-004',
    nombre: 'Saguaro Mini Trek',
    descripcion: 'Botita de trekking para pequeños aventureros. Agarre y protección para explorar la naturaleza.',
    precio: 39990,
    categoria: 'nino',
    tipo: 'trekking',
    imagenes: ['/products/n-trek-1.jpg'],
    tallas: [
      { talla: 28, stock: 6 },
      { talla: 29, stock: 8 },
      { talla: 30, stock: 10 },
      { talla: 31, stock: 12 },
      { talla: 32, stock: 10 },
      { talla: 33, stock: 8 },
    ],
    colores: ['Marron', 'Negro', 'Azul'],
    caracteristicas: ['Suela gruesa', 'Tobillo protegido', 'Resistente agua', 'Facil ajuste'],
    destacado: false,
    nuevo: false,
  },
]

export const featuredProducts = products.filter(p => p.destacado)
export const newProducts = products.filter(p => p.nuevo)
export const discountedProducts = products.filter(p => p.descuento)

export const getProductsByCategory = (categoria: string) => 
  products.filter(p => p.categoria === categoria)

export const getProductById = (id: string) => 
  products.find(p => p.id === id)

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('es-CL', {
    style: 'currency',
    currency: 'CLP',
    minimumFractionDigits: 0,
  }).format(price)
}
